apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory_manager
  labels:
    app: inventory_manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory_manager
  template:
    metadata:
      labels:
        app: inventory_manager
    spec:
      containers:
        - name: inventory_manager
          image: username/inventory_manager:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5